ccflags-y += -Idrivers/marvell/marvell-telephony/errorhandler
ccflags-y += -Idrivers/marvell/marvell-telephony/m3_rm
msocketk-objs := portqueue.o msocket.o portq_cp.o portq_m3.o
obj-$(CONFIG_MRVL_MMP_MODEM)	+= msocketk.o
