ccflags-y += -Idrivers/marvell/marvell-telephony/shmem/

data-path-objs := psdatastub.o data_path_common.o data_path_v1.o data_path_v2.o psd_rb_v2.o embms_netdev.o
obj-$(CONFIG_MRVL_MMP_MODEM) += data-path.o
